### ISSUE TITLE
the plain text structure of prose texts

### ISSUE THREAD

**Issue by djwrisley** [OpenMedFr/texts#10]
In correcting and formatting early work of one of last year's participant: [15th c version of the Fille du comte de Ponthieu](https://github.com/OpenMedFr/texts/blob/master/JAvesnesFilleB.txt), I wanted to clarify what our approach to the prose text should be.  

This text corresponds to pp. 51 sq in Brunel's [edition](https://archive.org/details/LaFilleDuComteDePontieuBrunel).  

Should we maintain the exact words per line (as in the first lines)? should we maintain the end of line word breaks?  The latter are typographic conventions.  The former? Any thoughts?

**Comment by GusRiva** [comment]
This is a complex issue. 

Respecting the lines of the original is good for readability and to be able to compare with the PDF. The alternatives, like dividing by folio or page make sense, but are hard to correct. I would be for the first option.
However, the end of line word breaks can be a huge nuisance for text processing. Maybe we could make a convention that broken words need to be transcribed as a whole in the line where they start? The next line will begin with the word following the one that had been broken.

**Comment by djwrisley** [comment]
I like your suggestion of respecting the lines of the original.  

This would facilitate any form of linking with the scans, e.g. downstream crowd correction with facing page pdf.  I suggest that we adopt the convention you suggest, namely that any broken word at the end of the line is kept on that line in its entirety with the hyphen is removed.  The next line begins as you mention.  

It seems to me that the main goal is to make sure that the plain text is reusable in a variety of scenarios, both alignment with pdf/manuscript scans and computational use. For me, precision in the latter is more important than in the former. 

This issue brings up other textual divisions (page, section, folio) that are both editorial and archival. 

A page number (PAGEV00P000) seems easy to insert into the flow of the text.  A section (# | ) such as a laisse, a chapter, etc is also easy to insert. 

A folio is less obvious, since it is archival can happens mid sentence in the edition.  A folio indication is nonetheless useful for aligning with manuscript images.  I would say if a folio breaks a word, that we follow the same convention as the printed end of line break above.  (NB: This does create a small loss of data for other downstream manipulation such as automatic conversion to TEIXML.)

An example would be, taken from the above mentioned edition. 

```
PAGEV01P51
§ Coment le conte de Ponthieu fu allié par mariage a
la fille du conte de Boulogne, de laquelle il ot une
fille qui fut mariee a Thibault de Dommarc.
# | 155
Selon la façon et maniere cy dessus recitee
PAGEV01P52
fina sa vie le noble et poissant conte de Pontieu, monseigneur
Jehan d’Avennez. Si succéda en la conté son filz, qui
moult ama le ciecle et le déduit de la chasse avec le trés
noble exercice d’armez, a quoy il se usitoit moult voulentiers. 
Et n’est pas a oublier que pour sez bonnez
FOLIO123B
euvrez et sez beaux fais, il eust une dame a espouse
de si noble et grande lignie comme la fille du conte de Boulogne
...
```

This text is only divided into sections, so # | divides it. But there is a question of knowing where the end of a prose text's paragraph is located.  Perhaps a blank line between paragraphs?

**Comment by djwrisley** [comment]
Or I guess paragraphs are separated by # |? as stanzas were in [CleomHas](https://github.com/OpenMedFr/texts/blob/master/CleomHas.txt).

**Comment by GusRiva** [comment]
Coming back to this issue after a while, I agree with all of the above. Paragraphs could be separated by # | , like stanzas. The same  signs followed by a number means a numbered section change.
I could start moving the consensus of this thread to the wiki page.
